import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Card from "../components/Card/Card";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center gap-10 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Card />
        <Card />
        <Card />
      </main>
    </>
  );
};

export default Home;
