import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Card from "../components/Card/Card";

export type Room = {
  id: number;
  name: string;
  status: boolean;
  auto: boolean;
  brightness: number;
  ldr?: number;
};

const rooms: Room[] = [
  {
    id: 1,
    name: "living room",
    status: false,
    auto: false,
    brightness: 20,
  },
  {
    id: 2,
    name: "bedroom",
    status: false,
    auto: false,
    brightness: 20,
  },
  {
    id: 3,
    name: "kitchen",
    status: false,
    auto: false,
    brightness: 20,
  },
];

const Home: NextPage = () => {
  const [roomOne, setRoomOne] = useState<Room>(rooms[0] as Room);
  const [roomTwo, setRoomTwo] = useState<Room>(rooms[1] as Room);
  const [roomThree, setRoomThree] = useState<Room>(rooms[2] as Room);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center gap-10 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Card room={roomOne} setRoom={setRoomOne} />
        <Card room={roomTwo} setRoom={setRoomTwo} />
        <Card room={roomThree} setRoom={setRoomThree} />
      </main>
    </>
  );
};

export default Home;
